server:
  port: 8080
  # graceful shutdown makes sure we have time to finish any ongoing rest requests before terminating
  # default value will be 30s before terminating
  shutdown: graceful

spring:
  threads:
    virtual:
      enabled: true # To enable virtual threads in Spring Boot 3.2 we just need to set this property
  application:
    name: playground

  #Configuración de la base de datos PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/playground-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  # Configuración de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update # Modo de actualización automática del esquema de la base de datos (update, create, none, ...)
    show-sql: true # Muestra las consultas SQL generadas por Hibernate

  flyway:
    enabled: false

  liquibase:
    drop-first: true
    enabled: true
    url: jdbc:postgresql://localhost:5432/playground-db
    user: postgres
    password: postgres
    change-log: classpath:/db/db.changelog-master.yaml


# Configuración para esperar a la base de datos antes de inciar la aplicación
spring.cloud.config:
  fail-fast: true

#Configuración del logging
logging:
  level:
    com.zaxxer.hikari: DEBUG